### ISSUE TITLE
Client.Common.Net.CRLFSocket.ReceiveCallback: SocketException

### ISSUE THREAD

**Issue by typewriter** [p2pquake/epsp-peer-cs#187]
```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=既存の接続はリモート ホストに強制的に切断されました。
  Source=System.Net.Sockets
  スタック トレース:
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 191
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CaptureOrComplete(ExecutionContext& cachedContext, Boolean returnContext)
   at System.Net.ContextAwareResult.FinishPostingAsyncOp(CallbackClosure& closure)
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 191
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

  | 名前 | 値 | 種類
-- | -- | -- | --
◢ | $exception | {"既存の接続はリモート ホストに強制的に切断されました。"} | System.Net.Sockets.SocketException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | ErrorCode | 10054 | int
  | HResult | -2147467259 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "既存の接続はリモート ホストに強制的に切断されました。" | string
  | NativeErrorCode | 10054 | int
  | SocketErrorCode | ConnectionReset | System.Net.Sockets.SocketError
  | Source | "System.Net.Sockets" | string

**Comment by typewriter** [comment]
Fixed in https://github.com/p2pquake/epsp-peer-cs/commit/dfd08deda66ed1ef228dfb5de3fd9e66cf6e1d4a
