### ISSUE TITLE
WpfClient: エラー画面等なくアプリが強制終了することがある

### ISSUE THREAD

**Issue by typewriter** [p2pquake/epsp-peer-cs#192]

**Comment by typewriter** [comment]
発生日時: 2022/02/06 13:16
発生条件: 地震感知情報の受信中

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  スタック トレース:
   場所 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   場所 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   場所 Client.Peer.Manager.Peer.Socket_ReadLine(Object sender, ReadLineEventArgs e) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\Peer.cs):行 73
   場所 Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 264
   場所 Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 231
   場所 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- 直前の場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   場所 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   場所 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

  この例外は、最初にこの呼び出し履歴 
    System.Collections.Generic.LinkedList<T>.Enumerator.MoveNext()
    System.Linq.Enumerable.EnumerablePartition<TSource>.MoveNext()
    System.Linq.Lookup<TKey, TElement>.Create(System.Collections.Generic.IEnumerable<TElement>, System.Func<TElement, TKey>, System.Collections.Generic.IEqualityComparer<TKey>)
    System.Linq.GroupedEnumerable<TSource, TKey>.GetEnumerator()
    System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TKey>, System.Func<TSource, TElement>, System.Collections.Generic.IEqualityComparer<TKey>)
    Client.App.Userquake.Aggregator.CalcMaxAreaRate(System.Collections.Generic.IEnumerable<Client.App.Userquake.Userquake>, System.Collections.Generic.IReadOnlyDictionary<string, int>) (Aggregator.cs 内)
    Client.App.Userquake.Aggregator.CalcConfidence(System.Collections.Generic.IEnumerable<Client.App.Userquake.Userquake>, System.Collections.Generic.IReadOnlyDictionary<string, int>) (Aggregator.cs 内)
    System.Linq.Enumerable.Max<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, int>)
    Client.App.Userquake.Aggregator.Evaluate(System.Collections.Generic.ICollection<Client.App.Userquake.Userquake>, System.Collections.Generic.IReadOnlyDictionary<string, int>) (Aggregator.cs 内)
    Client.App.Userquake.Aggregator.AddUserquake(System.DateTime, string, System.Collections.Generic.IReadOnlyDictionary<string, int>) (Aggregator.cs 内)
    ...
    [呼び出し履歴が切り捨てられました] でスローされました

内部例外 1:
InvalidOperationException: Collection was modified after the enumerator was instantiated.
=====
   場所 System.Collections.Generic.LinkedList`1.Enumerator.MoveNext()
   場所 System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   場所 System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   場所 System.Linq.GroupedEnumerable`2.GetEnumerator()
   場所 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   場所 Client.App.Userquake.Aggregator.CalcMaxAreaRate(IEnumerable`1 userquakes, IReadOnlyDictionary`2 areaPeers) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs):行 158
   場所 Client.App.Userquake.Aggregator.CalcConfidence(IEnumerable`1 userquakes, IReadOnlyDictionary`2 areaPeers) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs):行 114
   場所 System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   場所 Client.App.Userquake.Aggregator.Evaluate(ICollection`1 userquakes, IReadOnlyDictionary`2 areaPeers) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs):行 83
   場所 Client.App.Userquake.Aggregator.AddUserquake(DateTime at, String areaCode, IReadOnlyDictionary`2 areaPeers) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs):行 51
   場所 Client.Peer.Manager.PeerManager.RaiseUserquakeEvent(Packet packet) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\PeerManager.cs):行 372
   場所 Client.Peer.Manager.PeerManager.Peer_ReadLine(Object sender, ReadLineEventArgs e) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\PeerManager.cs):行 129
```

```
Application: P2PQuake.DEBUGBUILD.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.LinkedList`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   at Client.App.Userquake.Aggregator.CalcAreaConfidences(IEnumerable`1 userquakes, IReadOnlyDictionary`2 areaPeers) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs:line 195
   at Client.App.Userquake.Aggregator.Evaluate(ICollection`1 userquakes, IReadOnlyDictionary`2 areaPeers) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs:line 89
   at Client.App.Userquake.Aggregator.AddUserquake(DateTime at, String areaCode, IReadOnlyDictionary`2 areaPeers) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\Userquake\Aggregator.cs:line 51
   at Client.App.MediatorContext.<.ctor>b__98_5(Object s, EPSPUserquakeEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\MediatorContext.cs:line 134
   at Client.App.MediatorContext.<.ctor>b__98_1(Object s, EPSPUserquakeEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\App\MediatorContext.cs:line 119
   at Client.Peer.Context.PeerManager_OnUserquake(Object sender, EPSPUserquakeEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Context.cs:line 61
   at Client.Peer.Manager.PeerManager.RaiseUserquakeEvent(Packet packet) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\PeerManager.cs:line 371
   at Client.Peer.Manager.PeerManager.RaiseDataEvent(Packet packet) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\PeerManager.cs:line 152
   at Client.Peer.Manager.PeerManager.Peer_ReadLine(Object sender, ReadLineEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\PeerManager.cs:line 127
   at Client.Peer.Manager.Peer.State_ReadLine(Object sender, ReadLineEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\Peer.cs:line 54
   at Client.Peer.State.AbstractState.Relay(Peer peer, CRLFSocket socket, Packet packet) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\State\AbstractState.cs:line 185
   at Client.Peer.State.AbstractState.NotifyUserQuake(Peer peer, CRLFSocket socket, Packet packet) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\State\AbstractState.cs:line 44
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Client.Peer.Manager.Peer.Socket_ReadLine(Object sender, ReadLineEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Peer\Manager\Peer.cs:line 72
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 187
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```
