### ISSUE TITLE
Client: サーバとの通信中に異常終了することがある

### ISSUE THREAD

**Issue by typewriter** [p2pquake/epsp-peer-cs#220]
例外情報 x3 

ログ出力オフのため発生条件不明

```
Application: P2PQuake.DEBUGBUILD.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Client.Client.State.AbstractState.RequireAllowVersion(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 22
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\ClientContext.cs:line 130
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 187
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  スタック トレース:
   場所 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   場所 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   場所 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   場所 Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\ClientContext.cs):行 130
   場所 Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 264
   場所 Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 187
   場所 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- 直前の場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   場所 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   場所 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

  この例外は、最初にこの呼び出し履歴 
    Client.Client.State.AbstractState.AcceptedEcho(Client.Client.IClientContextForState, Client.Common.Net.CRLFSocket, Client.Common.Net.Packet) (AbstractState.cs 内) でスローされました

内部例外 1:
InvalidOperationException: Operation is not valid due to the current state of the object.
"   場所 Client.Client.State.AbstractState.AcceptedEcho(IClientContextForState context, CRLFSocket socket, Packet packet) (C:\\Users\\Administrator\\Documents\\epsp-peer-cs\\Client\\Client\\State\\AbstractState.cs):行 120"
```

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  スタック トレース:
   場所 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   場所 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   場所 Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\ClientContext.cs):行 132
   場所 Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 264
   場所 Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 231
   場所 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- 直前の場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   場所 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   場所 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

  この例外は、最初にこの呼び出し履歴 
    Client.Client.State.AbstractState.AcceptedEcho(Client.Client.IClientContextForState, Client.Common.Net.CRLFSocket, Client.Common.Net.Packet) (AbstractState.cs 内) でスローされました

内部例外 1:
InvalidOperationException: Operation is not valid due to the current state of the object.
"   場所 Client.Client.State.AbstractState.AcceptedEcho(IClientContextForState context, CRLFSocket socket, Packet packet) (C:\\Users\\Administrator\\Documents\\epsp-peer-cs\\Client\\Client\\State\\AbstractState.cs):行 120"
```

**Comment by typewriter** [comment]
リリースビルド

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  スタック トレース:
   場所 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   場所 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   場所 Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\ClientContext.cs):行 132
   場所 Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 264
   場所 Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs):行 231
   場所 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- 直前の場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   場所 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   場所 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

  この例外は、最初にこの呼び出し履歴 
    Client.Client.State.AbstractState.RequireAllowVersion(Client.Client.IClientContextForState, Client.Common.Net.CRLFSocket, Client.Common.Net.Packet) (AbstractState.cs 内) でスローされました

内部例外 1:
InvalidOperationException: Operation is not valid due to the current state of the object.
   場所 Client.Client.State.AbstractState.RequireAllowVersion(IClientContextForState context, CRLFSocket socket, Packet packet) (C:\Users\Administrator\Documents\epsp-peer-cs\Client\Client\State\AbstractState.cs):行 22
```

**Comment by typewriter** [comment]
リリースビルド

```
Application: P2PQuake.exe
CoreCLR Version: 5.0.1522.11506
.NET Version: 5.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot be operated in FinishedState
   at Client.Client.State.AbstractState.AllocatePeerId(IClientContextForState context, CRLFSocket socket, Packet packet)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e)
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes)
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by typewriter** [comment]
リリースビルド？ (0.9.2)

```
Application: P2PQuake.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Specified method is not supported.
   at Client.Client.State.AbstractState.IncorrectRequestError(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 186
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\ClientContext.cs:line 118
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by typewriter** [comment]
リリースビルド？ (0.9.2)  起動していた 4 つとも異常終了した

```
レベル	日付と時刻	ソース	イベント ID	タスクのカテゴリ
エラー	2022/09/08 2:00:23	Application Error	1000	(100)	"障害が発生しているアプリケーション名: P2PQuake.exe、バージョン: 0.35.0.5、タイム スタンプ: 0x62cf0990

Application: P2PQuake.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot be operated in FinishedState
   at Client.Client.State.AbstractState.AllocateTemporaryPeerId(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\ClientContext.cs:line 118
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


エラー	2022/09/08 2:00:07	Application Error	1000	(100)	"障害が発生しているアプリケーション名: P2PQuake.exe、バージョン: 0.35.0.5、タイム スタンプ: 0x62cf0990

エラー	2022/09/08 2:00:07	Application Error	1000	(100)	"障害が発生しているアプリケーション名: P2PQuake.exe、バージョン: 0.35.0.5、タイム スタンプ: 0x62cf0990

Application: P2PQuake.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot be operated in FinishedState
   at Client.Client.State.AbstractState.AcceptedEcho(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 120
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\ClientContext.cs:line 118
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


Application: P2PQuake.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot be operated in ConnectedState
   at Client.Client.State.AbstractState.NoticeAllowVersion(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 32
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\ClientContext.cs:line 118
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


エラー	2022/09/08 1:55:48	Application Error	1000	(100)	"障害が発生しているアプリケーション名: P2PQuake.exe、バージョン: 0.35.0.5、タイム スタンプ: 0x62cf0990

Application: P2PQuake.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot be operated in RequireTemporaryPeerIdState
   at Client.Client.State.AbstractState.NoticeAllowVersion(IClientContextForState context, CRLFSocket socket, Packet packet) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\State\AbstractState.cs:line 32
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Client.Client.ClientContext.ProcessData(Object sender, ReadLineEventArgs e) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Client\ClientContext.cs:line 118
   at Client.Common.Net.CRLFSocket.ProcessReceiveData(Int32 receiveBytes) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 264
   at Client.Common.Net.CRLFSocket.ReceiveCallback(IAsyncResult ar) in C:\Users\takuya\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\CRLFSocket.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

パケットキャプチャファイル: [packet_tcp6910_202209080200.zip](https://github.com/p2pquake/epsp-peer-cs/files/9527482/packet_tcp6910_202209080200.zip)

**Comment by typewriter** [comment]
`FinishedState` での異常は以下の順序で発生していると推測。

1. サーバーと通信中、何らかの要因で 90 秒以上が経過
2. Client.App.MaintainTimer#Tick において、サーバ通信が中断されたと判定
3. 次の #Tick において、再接続
4. Client.Client.ClientContext#Join において、サーバーと接続済みのため接続処理に失敗して `FinishedState` に遷移
5. ここでサーバーからのデータを受信すると、 `FinishedState` で処理するため InvalidOperationException をスロー
