### ISSUE TITLE
スリープ復帰時に異常終了する (Cannot connect in ConnectingState)

### ISSUE THREAD

**Issue by typewriter** [p2pquake/epsp-peer-cs#268]
```
Application: P2PQuake.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Cannot connect in ConnectingState
   at Client.App.State.AbstractState.Connect(MediatorContext mediatorContext, IClientContext clientContext, IPeerContext peerContext)
   at Client.App.MediatorContext.MaintainTimer_RequireConnect(Object sender, EventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by typewriter** [comment]
duplicate: #232  (already fixed, not released yet)
