### ISSUE TITLE
IP アドレス変化による再接続時、ポートを Listen しているが Accept できない状態となる

### ISSUE THREAD

**Issue by typewriter** [p2pquake/epsp-peer-cs#269]
サーバ上の EPSP クライアントで観測

```
2022-07-21 21:54:16,997 DEBUG CLI [40]: 実行するメソッド: AddressChangedError
--
2022-07-21 21:54:16,998 DEBUG CLI [40]: ClientContext_OperationCompleted: Restartable, RETURNED_ADDRESS_CHANGED
2022-07-21 21:54:16,998 INFO  CLI [40]: IPアドレスが変化しているため、再接続します。
2022-07-21 21:54:17,000 DEBUG CLI [44]: 切断されました。
2022-07-21 21:54:17,000 DEBUG CLI [44]: Connected: true
2022-07-21 21:54:17,001 INFO  CLI [40]: ピア接続をすべて切断しました（接続数: 0）
2022-07-21 21:54:17,001 INFO  CLI [40]: State changed: DisconnectedState
2022-07-21 21:54:17,001 DEBUG CLI [40]: 実行後の状態: FinishedState
2022-07-21 21:54:17,001 DEBUG CLI [39]: リッスン中断要求
2022-07-21 21:54:17,001 DEBUG CLI [39]: リッスン中断要求
2022-07-21 21:54:17,001 DEBUG CLI [39]: インスタンス初期化 (ポート: 9991)
2022-07-21 21:54:17,002 DEBUG CLI [39]: リッスン (IPv4 TCP ポート: 9991)
2022-07-21 21:54:17,002 INFO  CLI [39]: State changed: ConnectingState
2022-07-21 21:54:17,002 DEBUG CLI [44]: 切断しました。
2022-07-21 21:54:17,002 DEBUG CLI [44]: ピアから切断されました: 1894
2022-07-21 21:54:17,002 DEBUG CLI [44]: 切断処理完了。
2022-07-21 21:54:17,002 DEBUG CLI [44]: Tick
2022-07-21 21:54:17,004 WARN  CLI [40]: 対ピア接続受け入れ時にエラーが発生しました。無視します。
System.Net.Sockets.SocketException (125): Operation canceled
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
at Client.Common.Net.AsyncListener.AcceptInfinite() in /app/epsp-peer-cs/Client/Common/Net/AsyncListener.cs:line 48
2022-07-21 21:54:17,005 DEBUG CLI [40]: リッスン処理終了
2022-07-21 21:54:17,012 DEBUG CLI [39]: 接続しました: p2pquake.ddo.jp:6910
2022-07-21 21:54:17,012 DEBUG CLI [39]: 受信データ: 211 1
2022-07-21 21:54:17,012 DEBUG CLI [39]: 現在の状態: ConnectedState
2022-07-21 21:54:17,012 DEBUG CLI [39]: 実行するメソッド: RequireAllowVersion
2022-07-21 21:54:17,012 DEBUG CLI [39]: 実行後の状態: NotifyProtocolVersionState
2022-07-21 21:54:17,012 DEBUG CLI [39]: 送信データ: 131 1 0.35:P2PQ_SharpClient:compatible_0.35.004
2022-07-21 21:54:17,015 DEBUG CLI [39]: 受信データ: 212 1 0.32:EPSP_Server_CS:alpha_1
2022-07-21 21:54:17,015 DEBUG CLI [39]: 現在の状態: NotifyProtocolVersionState
2022-07-21 21:54:17,015 DEBUG CLI [39]: 実行するメソッド: NoticeAllowVersion
2022-07-21 21:54:17,015 DEBUG CLI [39]: 実行後の状態: RequireTemporaryPeerIdState
2022-07-21 21:54:17,015 DEBUG CLI [39]: 送信データ: 113 1
2022-07-21 21:54:17,023 DEBUG CLI [40]: 受信データ: 233 1 1490
2022-07-21 21:54:17,024 DEBUG CLI [40]: 現在の状態: RequireTemporaryPeerIdState
2022-07-21 21:54:17,024 DEBUG CLI [40]: 実行するメソッド: AllocateTemporaryPeerId
2022-07-21 21:54:17,025 DEBUG CLI [40]: 実行後の状態: RequirePortScanState
2022-07-21 21:54:17,025 DEBUG CLI [40]: 送信データ: 114 1 1490:9991
2022-07-21 21:54:17,030 DEBUG CLI [37]: 受信データ: 234 1 1
2022-07-21 21:54:17,030 DEBUG CLI [37]: 現在の状態: RequirePortScanState
2022-07-21 21:54:17,030 DEBUG CLI [37]: 実行するメソッド: ReceivePortCheckResult
```

→ コード234（ポート開放チェック返答）で 1 （成功）となっているが、接続受け入れのログが出力されていない。 Listen したまま Accept 処理がされなくなっていることがわかる。

**Comment by typewriter** [comment]
この不具合と無関係かもしれないが、 App.State.MaintenanceState#Completed と App.MaintainTimer#MediatorContext_Completed の両方で再接続処理が走っている。ただし、 #232 の修正で片方が無視されていて、結果的に問題なく実行され続ける。

```
2022-07-30 11:26:40,469 INFO  CLI [8|Client.App.State.MaintenanceState]: IPアドレスが変化しているため、再接続します。
2022-07-30 11:26:40,471 INFO  CLI [8|Client.App.State.MaintenanceState]: ピア接続をすべて切断しました（接続数: 0）
2022-07-30 11:26:40,472 INFO  CLI [8|CLI.Command.LoggerCommand]: State changed: DisconnectedState
2022-07-30 11:26:40,474 DEBUG CLI [8|Client.App.MaintainTimer]: 再接続しましょう。
2022-07-30 11:26:40,474 DEBUG CLI [5|Client.App.MaintainTimer]: Tick
2022-07-30 11:26:40,478 DEBUG CLI [8|Client.Client.ClientContext]: 実行後の状態: FinishedState
2022-07-30 11:26:40,479 DEBUG CLI [7|Client.App.MediatorContext]: RequireDisconnectAllPeers
2022-07-30 11:26:40,479 DEBUG CLI [5|Client.App.MediatorContext]: RequireConnect
2022-07-30 11:26:40,484 DEBUG CLI [5|Client.App.MediatorContext]: Listening...
2022-07-30 11:26:40,487 DEBUG CLI [5|Client.Common.Net.AsyncListener]: リッスン中断要求
2022-07-30 11:26:40,483 DEBUG CLI [7|Client.Common.Net.AsyncListener]: リッスン中断要求
2022-07-30 11:26:40,488 DEBUG CLI [5|Client.Common.Net.AsyncListener]: インスタンス初期化 (ポート: 12345)
2022-07-30 11:26:40,489 WARN  CLI [8|Client.Common.Net.AsyncListener+<AcceptInfinite>d__8]: 対ピア接続受け入れ時にエラーが発生しました。無視します。
System.Net.Sockets.SocketException (995): スレッドの終了またはアプリケーションの要求によって、I/O 処理は中止されました。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Client.Common.Net.AsyncListener.AcceptInfinite() in C:\Users\takuy\Dropbox\Private\p2pq\epsp-peer-cs\Client\Common\Net\AsyncListener.cs:line 48
2022-07-30 11:26:40,490 DEBUG CLI [7|Client.App.MediatorContext]: RequireConnect
2022-07-30 11:26:40,495 DEBUG CLI [5|Client.Common.Net.AsyncListener]: リッスン (IPv4 TCP ポート: 12345)
2022-07-30 11:26:40,506 DEBUG CLI [8|Client.Common.Net.AsyncListener+<AcceptInfinite>d__8]: リッスン処理終了
2022-07-30 11:26:40,511 DEBUG CLI [5|Client.App.MediatorContext]: Connecting...
2022-07-30 11:26:40,514 INFO  CLI [5|CLI.Command.LoggerCommand]: State changed: ConnectingState
```
